app/__init__.py
from flask import Flask

from app.errors.routes import error_404, error_403, error_401, error_500


def create_app():
    app = Flask(__name__)

    # Retrieve configuration information
    app.config.from_object('app.config.Config')

    # Initialization of blueprints
    from app.main import main_bp

    # Error handlers
    app.register_error_handler(404, error_404)
    app.register_error_handler(403, error_403)
    app.register_error_handler(401, error_401)
    app.register_error_handler(500, error_500)

    app.register_blueprint(main_bp)
    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

import app.main.routes

app/main/routes.py
from base64 import b64encode
from io import BytesIO

import cv2
import numpy as np
from PIL import Image
from flask import render_template, Response, flash
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from werkzeug.exceptions import abort
from wtforms import FileField, SubmitField
from app.main import main_bp
from app.main.camera import Camera

import json
from flask import Response

from source.test_new_images import detect_mask_in_image
from source.video_detector import detect_mask_in_frame
from source.video_detector import labels

@main_bp.route("/get_mask_status")
def get_mask_statu():
    return Response(json.dumps(labels),  mimetype='application/json')

@main_bp.route("/")
def home_page():
    return render_template("home_page.html")


def gen(camera):

    while True:
        frame = camera.get_frame()
        frame_processed = detect_mask_in_frame(frame)
        frame_processed = cv2.imencode('.jpg', frame_processed)[1].tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_processed + b'\r\n')


@main_bp.route('/video_feed')
def video_feed():
    return Response(gen(
        Camera()
    ),
        mimetype='multipart/x-mixed-replace; boundary=frame')


def allowed_file(filename):
    ext = filename.split(".")[-1]
    is_good = ext in ["jpg", "jpeg", "png"]
    return is_good


@main_bp.route("/image-mask-detector", methods=["GET", "POST"])
def image_mask_detection():
    return render_template("image_detector.html",
                           form=PhotoMaskForm())


@main_bp.route("/image-processing", methods=["POST"])
def image_processing():
    form = PhotoMaskForm()

    if not form.validate_on_submit():
        flash("An error occurred", "danger")
        abort(Response("Error", 400))

    pil_image = Image.open(form.image.data)
    image = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)
    array_image = detect_mask_in_image(image)
    rgb_image = cv2.cvtColor(array_image, cv2.COLOR_BGR2RGB)
    image_detected = Image.fromarray(rgb_image, 'RGB')

    with BytesIO() as img_io:
        image_detected.save(img_io, 'PNG')
        img_io.seek(0)
        base64img = "data:image/png;base64," + b64encode(img_io.getvalue()).decode('ascii')
        return base64img


# form
class PhotoMaskForm(FlaskForm):
    image = FileField('Choose image:',
                      validators=[
                          FileAllowed(['jpg', 'jpeg', 'png'], 'The allowed extensions are: .jpg, .jpeg and .png')])

    submit = SubmitField('Detect mask')

app/templates/error.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container text-center">
        <h1>Error {{error}}</h1>
        <p class="lead">An errror occurred, please try again</p>
        <div class="row mt-5 d-flex justify-content-center">
            <a role="button" class="btn btn-lg btn-outline-info" href="/">Home page</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home_page.html
{% extends "template.html" %}
{% block content %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-12">
                <h2><center>Mask Detection and Analysis</center></h2>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div id="frame_container" class="row">
                    <div class="col-12">
                        <img src="/static/images/stay-safe.jpg"
                            class="img-thumbnail img-fluid mx-auto d-block">
                    </div>
                </div>
                <div class="row mt-3 mb-5">
                    <div class="col-6 d-flex justify-content-end">
                        <button id="start" onclick="start()" class="btn btn-outline-success"><i class="fa fa-video-camera"
                                                                                                aria-hidden="true"></i> Start
                        </button>
                    </div>
                    <div class="col-6 d-flex justify-content-start">
                        <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop"
                                                                                            aria-hidden="true"></i> Stop
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div id="chartContainer"></div>
            </div>
        </div>
        <div class="container-fluid">
            <hr>
            <div class="row">
                <h4>What is this?</h4>
            </div>
            <div class="row">
                <p>This is a mask detector, an algorithm based on deep neural networks that detects people through your
                    camera and write a bounding box around faces,
                    looking if they were masks or not. This is not for security purpose.</p>
            </div>
        </div>
    </div>
    
{% endblock %}
{% block custom_js %}
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<script>
$(document).ready(function(){
    $('#image-detector').attr('class', 'nav-item');
    $('#live').attr('class', 'nav-item active');
})

    function stop(){
        $("img").attr("src", "/static/images/stay-safe.jpg");
        $("#stop").attr("class","btn btn-danger active");

        $("#start").attr("class","btn btn-outline-success");
    }
    function start(){
        $("img").attr("src", "{{url_for('main.video_feed')}}");
        $("#start").attr("class","btn btn-success active");

        $("#stop").attr("class","btn btn-outline-danger");
    }

</script>

{% endblock %}

app/templates/image_detector.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-12">
            <h1>Try the mask detector on custom images</h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img src="/static/images/mask.jpg" id="image-preview" style="max-width:600px"
                     class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-12 d-flex justify-content-center">

                <form enctype="multipart/form-data" id="image-form" method="POST">
                    <div class="row" id="form-row">
                        <div class="col-12">
                            {{ form.csrf_token() }}

                            {{ form.image.label(class="custom-file-label") }}
                            {% if form.image.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.image.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="custom-file">
                                {{ form.image(class="custom-file-input",
                                id="new-image", onchange="previewImage(event)") }}
                            </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-12 d-flex justify-content-center">
                            {{ form.submit(class="btn btn-primary", id ="submit", disabled=True)}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <hr>
        <div class="row">
            <h4>What is this?</h4>
        </div>
        <div class="row">
            <p>This is a mask detector, an algorithm based on deep neural networks that detects people in images and
                write a bounding box around faces, looking if they were masks or not. This is not for security
                purpose.</p>
            <p>If you are interested in more details, check this post I wrote!</p>
        </div>
        <div class="row">
            <h4>Who I am</h4>
        </div>
        <div class="row mb-5">
            <p>I'm Galileo Parise, data scientist and matematician, and I've developed what you see during Italy's
                second lockdown in November, in which I had lots of free time. If you are interested in this and ohter
                stories,
                you can follow me on Linkedin and on Medium.
                Hoping to get soon over this situation,
                I hope you all good health:</p>
            <p class="d-flex mx-auto lead text-danger"><strong>please, stay safe and wear a mask</strong>.</p>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
var previewImage = function(event) {
    var element_id = "image-preview";
    var preview = document.getElementById(element_id);
    preview.src = URL.createObjectURL(event.target.files[0]);
    preview.style.display = "block";
    $("#submit").prop("disabled",false);
};
$(document).ready(function(){
    $('#live').attr('class', 'nav-item');
    $('#image-detector').attr('class', 'nav-item active');
})
$(function() {
        $("#submit").each(function(index){
            $(this).on('click', function(e) {

                var url = "{{ url_for('main.image_processing') }}";

                // Form data
                var formData = new FormData();

                // Add form data
            $('#image-form').serializeArray().forEach(
                function(item, index) {
                    formData.append(item.name, item.value);
                }
            );
                // Add the files
                var image = $('#new-image')[0].files[0];
                formData.append('image', image);

                // AJAX query to the endpoint for deletion
                $.ajax({
                    type: "POST", // POST HTTP
                    url:  url +'',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function(response) {

                        $("#image-preview").attr("src", response);
                        $("#submit").replaceWith('<button class="btn btn-success"><i class="fa fa-check-circle" onclick="location.reload()" aria-hidden="true"></i> Done!</button>');
                        $("#form-row").remove();
                    },
                    error: function(response){
                        location.reload();
                        // Redirect to this page
                    }
                });

                return false;
            })
        })
    })
</script>

{% endblock %}

app/templates/template.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <title>Mask detector live</title>
    <script>
        window.onload = function () {
            setInterval(function(){ 
                
                $.get( "http://127.0.0.1:5000/get_mask_status", function( data ) {
                    $( ".result" ).html( data );
                    console.log(data)
                    var chart = new CanvasJS.Chart("chartContainer", {
                        exportFileName: "Doughnut Chart",
                        title:{
                            text: "Mask Analysis"
                        },
                        legend:{
                            cursor: "pointer",
                            itemclick: explodePie
                        },
                        data: [{
                            type: "doughnut",
                            innerRadius: 50,
                            showInLegend: true,
                            toolTipContent: "<b>{name}</b>: (#percent%)",
                            indexLabel: "{name} - #percent%",
                            dataPoints: [
                                { y: data[1], name: "Mask" },
                                { y: data[0], name: "No Mask" }
                            ]
                        }]
                    });
                    chart.render();
                    function explodePie (e) {
                        if(typeof (e.dataSeries.dataPoints[e.dataPointIndex].exploded) === "undefined" || !e.dataSeries.dataPoints[e.dataPointIndex].exploded) {
                            e.dataSeries.dataPoints[e.dataPointIndex].exploded = true;
                        } else {
                            e.dataSeries.dataPoints[e.dataPointIndex].exploded = false;
                        }
                        e.chart.render();
                    }
                });
            }, 500);
        }
        </script>
    <style>
        .footer-link{ color: inherit; }
        .footer-link:hover{ color: inherit; }
        body {
            margin: 0;
        }

        .wrapper {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .footer {
            margin-top: auto;
        }

        .jumbotron {
            padding: 30px;
        }
    </style>
</head>
<body>
<div class="wrapper">
    <div class="header">

        <!--banner-->
        <div class="header-row badge-dark" id="header-row" style=" overflow:hidden;">
            <div class="container-fluid text-center">
                <div class="row ">
                    <div class="col-12">
                        <p class="text-white my-1 p-3 text-center">
                            HCI Project: 171080066 (Yash S. Jain), 171080055 (Yash R.Jain)
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="content">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% endif %}
        {% endwith %}

        <!--add custom content with inheritance-->
        {% block content %}
        {% endblock %}
    </div>
</div>
<!-- jQuery, Popper.js, and Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
{% block custom_js %}
{% endblock %}
</body>
</html>